name: Publish package to GitHub Packages after merged to master
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.GITHUB_TRIGGER_REF }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@adscore'
      - name: Install dependencies
        run: npm clean-install
      - name: Build
        env: # temporary workaround for "Error: error:0308010C:digital envelope routines::unsupported" in Node lts / 18
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm run build && npm run babel
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Release
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          npm publish

