name: Publish package to GitHub Packages after merged to master
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@adscore'
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3.3.2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install node modules
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci
      # Build the lib
      - run: npm run build && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
